// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCru44iSSsxdxVK5Ge0h2OVqCFc94F6W8E',
    appId: '1:958242886503:web:1c6bc5c9feeb736e6f95c2',
    messagingSenderId: '958242886503',
    projectId: 'fitness-app-ee4b9',
    authDomain: 'fitness-app-ee4b9.firebaseapp.com',
    storageBucket: 'fitness-app-ee4b9.firebasestorage.app',
    measurementId: 'G-4H2B4XJJ3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiM8BdD1yN_kYYnPcCpPO2xayOZ3n0SYI',
    appId: '1:958242886503:android:082ffd63b8f558166f95c2',
    messagingSenderId: '958242886503',
    projectId: 'fitness-app-ee4b9',
    storageBucket: 'fitness-app-ee4b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdNl6NkmHNVzCwRh1V9_Q5vqdVHV8deNA',
    appId: '1:958242886503:ios:0c09cc8723d9c5616f95c2',
    messagingSenderId: '958242886503',
    projectId: 'fitness-app-ee4b9',
    storageBucket: 'fitness-app-ee4b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdNl6NkmHNVzCwRh1V9_Q5vqdVHV8deNA',
    appId: '1:958242886503:ios:0c09cc8723d9c5616f95c2',
    messagingSenderId: '958242886503',
    projectId: 'fitness-app-ee4b9',
    storageBucket: 'fitness-app-ee4b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCru44iSSsxdxVK5Ge0h2OVqCFc94F6W8E',
    appId: '1:958242886503:web:6cb2a9b1e877ac466f95c2',
    messagingSenderId: '958242886503',
    projectId: 'fitness-app-ee4b9',
    authDomain: 'fitness-app-ee4b9.firebaseapp.com',
    storageBucket: 'fitness-app-ee4b9.firebasestorage.app',
    measurementId: 'G-JVJE2HBYSJ',
  );
}
